### ISSUE TITLE
Bestiary Bug: monster_id

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#118]
I was using monster names to direct you to the bestiary/<monster_name>
But if the name has a space, such as "Alpha Wolf", then HTML is directing me to bestiary/Alpha
This is causing problems so I had to give a temporary monster_id to each one and have it direct to their id number instead.

**Comment by jimmy-gnahz** [comment]
List of monsters will be recorded in the database eventually

**Comment by klondikemarlen** [comment]
Created a new issue to reference the creation of this object. #166 Please comment and explain the specs you want @elthran.
