### ISSUE TITLE
Prevent the user from typing in URL to move around the game

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#133]
Right now the user can type in any game URL to go to that place in the game. It needs to be fixed eventually.

**Comment by klondikemarlen** [comment]
I did a bunch of work on this! https://github.com/elthran/RPG-Game/tree/issue133_prevent_url ... I need to update the locations.py code though or it won't work.

**Comment by klondikemarlen** [comment]
Concept is working ... the implementation will need some testing but I will let close this for now.
