### ISSUE TITLE
We Need a Way for the Game to 'Refresh'

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#139]
Whenever you go to pretty much any page on the site, it should send you any notifications and then refresh the notifications (maybe that you've beaten a quest or earned an achievement). It should check if you have any of these, send it to you, then clear your notification log.

Same with leveling up. The game should check on every page if you've leveled up (maybe you just completed a quest from any dialogue, found an item, discovered a new zone, etc.). There are do many ways to gain exp, that the level_up function should pretty much run of every page click.

How do we go about running a function that checks all of this stuff on every page click?

**Comment by klondikemarlen** [comment]
I have some theories ... see #240. I am migrating this data there.
