### ISSUE TITLE
New refresh_character functions.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/RPG-Game#141]
Login one should update most stats but not current ones. (ie, current_health).
Leveling up should update everything.

**Comment by elthran** [comment]
We should have health, endurance, sanctity all grow slowly over time (at different rates).
Leveling up should fully refresh all of them.
We could even have like a nightly "reset" that brings dead characters back to low health and gives a small boost to everything. That way you play a bit during the day, maybe you die maybe not, but you log in the next day and you are "refreshed" more than you would after just a few hours.

**Comment by klondikemarlen** [comment]
Nice that sounds good. We will need a better timing engine. And a _single_ thread that updates all characters at once off of this thread. Not different ones for each character.
