### ISSUE TITLE
Move ALL scripts to scripts.js

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#142]
Find out how to let them have access to python variables

**Comment by klondikemarlen** [comment]
I think you want a separate render_template(...) each time it needs to be rendered in app.py.
Or to build the JS as separate from the game rendering ... and then write an
"abstraction_lv1/build_code.py/build_code.cmd" set for it and do the rendering manually.

**Comment by klondikemarlen** [comment]
Closing as no longer relevant. I believe than almost all scripts are now in script.js
