### ISSUE TITLE
Proficiencies are not adopting the child classes

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#175]
all proficiencies are the class Proficiency(Base) and none have any child classes [such as AttackDamage(Proficiency)]

**Comment by klondikemarlen** [comment]
In proficiencies.py see:
def __init__(self):
        
        self.attack_damage = Proficiency("Attack damage", "", "Strength", "Offense").

This should really say:
def __init__(self):
        self.attack_damage = AttackDamage("Attack damage", "", "Strength", "Offense")

And should be in the proficiencies_template.py as:
def __init__(self):
        {%- for prof in PROFICIENCY_INFORMATION %}
        self.{{ prof[0].lower().replace(' ', '_') }} = {{ prof[0].title().replate(" ", "") }}("{{ prof[0] }}", "{{ prof[1] }}", "{{ prof[2] }}", "{{ prof[3] }}")
        {%- endfor %}

**Comment by klondikemarlen** [comment]
I am considering updating PROFICIENCY_INFORMATION to be a dictionary so you can do:
prof.name, prof.class_name, prof.var_name, prof.description, prof.attribute etc.

**Comment by elthran** [comment]
Ya I found the cause but was having trouble writing it the right way. I even hardcoded some to the proper way in proficiencies.py but not inyour template file

**Comment by elthran** [comment]
Fixed!
