### ISSUE TITLE
Inventory very bug ridden

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#180]
Sometimes I can't equip anything, usually I can't unequip anything, and half the time I need to go to the home page for the items to take affect. Also, I can wear any unlimited amount of all item types.

**Comment by klondikemarlen** [comment]
It is only half ported to the database. I will see what I can do. And the command code is super old and not tested. I really really want to write a test suite for the actual website.

**Comment by elthran** [comment]
I just tried it on the server, and buying some items and then going to the home page crashes your entire account.

**Comment by klondikemarlen** [comment]
I am working on it in a separate branch. Still a long way to go.

**Comment by klondikemarlen** [comment]
Never version available eec5a4f921e849ca5f2953de9dbd55c38f1269a2.
