### ISSUE TITLE
Maybe we should gitignore the read-only files?

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#185]
On the plus side it would not add 700 unnecessary deletes or modifications each push.
On the negative side, you need to run the build_code code each time you pull (if you forget you might get weird errors).

Maybe have the build_code run everytime you run app.py in that case? Or just leave it as is?

**Comment by klondikemarlen** [comment]
Hmmm ... I was wondering about that too. I am leaning towards leaving as is. That way it is easier to see what changes you have made. Though running build_code.py when app.py runs might be a good idea too. It wouldn't be that hard either.

**Comment by klondikemarlen** [comment]
https://stackoverflow.com/a/13296949
import subprocess
subprocess.check_call(["C:\pathToYourProgram\yourProgram.exe", "your", "arguments", "comma", "separated"])

**Comment by klondikemarlen** [comment]
In app.py
import subprocess
subprocess.check_call([build_code.cmd])

**Comment by klondikemarlen** [comment]
Left as is.
