### ISSUE TITLE
I have a question about your code

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#193]
What do these two do? It seems that __iter__ allows you to now iterate over all the attributes inside this object (WHICH IS WHAT I REALLY WANTED EARLIER!!!). But i don't 100% understand how you were able to do it so nicely. And I don't understand "items" at all. What would you use it for? How do you even call it and use it?

![test](https://cloud.githubusercontent.com/assets/11773722/26252024/af73dbea-3ce1-11e7-88ae-1240ac1c2248.jpg)

**Comment by klondikemarlen** [comment]
When you do:
`for proficiency in hero.proficiencies` 

it calls `__iter__`

when you do:
`for key, value in hero.proficiencies.items():`

it calls `items`. I stole these from lists builtin and dict builtin :)

**Comment by elthran** [comment]
Thanks! Now I just need to read up on getattr
