### ISSUE TITLE
Login doesnt display stats until you click on profile

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#195]
I think this only happens when you delete the database before logging in.

**Comment by klondikemarlen** [comment]
I believe the problem occurs due to the swictch (in game.py) from `def update_proficiencies(self):` to `def refresh_proficiencies(self):`

**Comment by klondikemarlen** [comment]
I suggest starting a new branch to fix this issue. The issue #188 is part of this issue as well.
Branch update_prof suggested.

**Comment by klondikemarlen** [comment]
This involves Hero attributes:
Health
Sanctity
Experience
Endurance
Storage
And the Max/Min and Percent values of those attribs.

**Comment by klondikemarlen** [comment]
The Hero 
```
@validates(*)
def sync_*
```
Must be moved to Proficiencies as well.

**Comment by klondikemarlen** [comment]
And the Html in "layout.html" needs to be updated to poll "hero.proficiency.*_percent.

**Comment by elthran** [comment]
Ok weird? The experience one works fine. But if you have 0 experience it shows as full. But as long as you do'nt have 0 experience, then the bar fills up the correct amount? Let's talk about this on Skype because I do'nt understand the vaildators even after reading all about them.

**Comment by elthran** [comment]
Also, the others don't seem to work. Just experience...

**Comment by klondikemarlen** [comment]
As seen in #199 I believe that we should completely switch to "refresh_proficiencies" and port all the relevant content from "update_proficiencies".

Usage should look like:
#main usage in app.py
`hero.update()`

```
Class Hero:
    def update(self):
        self.proficiencies.update()

Class Proficiencies:
    def update(self):
        for proficiency in self:
            proficiency.update(self.hero)
```
