### ISSUE TITLE
Look up other players' profiles

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#197]
We have a user page already which displays information on every user. Now I want to practice more database and user inquiries so that you can click on an account in the user page and it brings you to a modified version of the home page which shows basic information about that user.

**Comment by elthran** [comment]
I'm bring Marlen in for help. My function is around Line 270ish of app.py

It's half working but it's not pulling all the values correctly, only some. I'm not sure why. Can you give me a hand?

**Comment by klondikemarlen** [comment]
Looks interesting :).
