### ISSUE TITLE
Go through game.py and remove redundancies or at least add comments

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#199]
- For example there is refresh_proficiencies and update_proficiencies but I don't know which one should be ran when or if they both even work anymore. They should be documented better. 
- The validators should be moved.
- The percent (health, sanctity, etc.) don't work anymore
- self.health_maximum is simply a redundancy of self.proficiencies.health.maximum

**Comment by elthran** [comment]
What is this? IF it's needed can you expand on the comments?
![test](https://cloud.githubusercontent.com/assets/11773722/26543900/49eccbde-4492-11e7-91bc-eb0074557061.jpg)

**Comment by elthran** [comment]
Is this a remnant of the old attribute system? Should it be deleted or is it still used somewhere?

![test](https://cloud.githubusercontent.com/assets/11773722/26543925/6880aab6-4492-11e7-837d-c24971c8df65.jpg)

**Comment by klondikemarlen** [comment]
Yep. That was a gimmick that we never used. Not ever :). It is quite clever though. Most other system use something like this. Particularly the Python builtin modules.

**Comment by klondikemarlen** [comment]
See #195 for everything related to "refresh_proficiencies" and "update_proficiencies".
