### ISSUE TITLE
Use real password obfustication scheme.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/RPG-Game#203]
Currently we are using a md5 ... which isn't really a password.
We can upgrade to something like bcrypt such as in:
https://www.twilio.com/docs/tutorials/account-verification-python-flask#building-blocks

**Comment by klondikemarlen** [comment]
Even better: http://dustwell.com/how-to-handle-passwords-bcrypt.html

**Comment by klondikemarlen** [comment]
from bcrypt import hashpw, gensalt
hashed = hashpw(plaintext_password, gensalt(log_rounds=20000)) #possibly decode('utf-8')?
if hashpw(password_attempt, hashed) == hashed:
    print "It matches"
else:
    print "It does not match"

**Comment by jimmy-gnahz** [comment]
Sure, I took that random piece of code containing md5 from a comment on stackoverflow, I believe.  
Interesting read btw! Thanks for sharing!

**Comment by klondikemarlen** [comment]
Yes. We would all need to install bcrypt
`pip install bcrypt`
and maybe some tweaking.
On the server I am pretty sure they already have bcrypt installed.

**Comment by klondikemarlen** [comment]
And I am unsure of the number of log_rounds. It might be higher now. Though for us we could probably just use the default of 12 forever :P

**Comment by elthran** [comment]
Is this resolved? Or has the issue been combined with another one?

**Comment by klondikemarlen** [comment]
It is good to go! (on https://github.com/elthran/RPG-Game/tree/security)
