### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#21]
Start with a basic one. On login page you can click "forgot password" and it will display a random username//password combo. Later we can upgrade it to emailing or something.

**Comment by elthran** [comment]
So for now, just have it so you can create a new password as long as you know a username

**Comment by klondikemarlen** [comment]
@elthran If you do the HTML I will do the database code.

**Comment by klondikemarlen** [comment]
This depends on #203. If we are going to be storing peoples data we need real security.

**Comment by klondikemarlen** [comment]
Fixed in  63a2054.
