### ISSUE TITLE
Completely messed up the login

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#210]
I moved some functionality from home() to login()

It fixed some bugs but caused many others. Can you help sort this out? 
![test](https://cloud.githubusercontent.com/assets/11773722/26713314/8e2c004e-479e-11e7-97f6-48a1cde040cf.jpg)

This was happening only when you visit home page. Was causing bugs. Now it happens on login. Causing different bugs.

**Comment by elthran** [comment]
Ok the bugs caused by mving them were greater than the previous bugs so i moved them back. but still needs to be addressed

**Comment by klondikemarlen** [comment]
Oh nice. I have and idea that I have been trying to implement slowly.
at the top of each function in app.py do a:
`hero = database.get_hero_by_id(session["hero_id"])`
and at the end of each app.py function (just before every return) do:
`database.update()`

This may fix all the problems and allow us to avoid using _global_ at all.
