### ISSUE TITLE
Less tables?

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/RPG-Game#215]
I would like to ask what you guys think about using less tables in the Database but with more data in each table. The current database uses **Joined Table Inheritance** and I am considering switching to **Single Table Inheritance**. See http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#basic-control-of-which-tables-are-queried. 

The process isn't very hard as demonstrated for the items.py file in branch https://github.com/elthran/RPG-Game/tree/issue215

**Comment by klondikemarlen** [comment]
Some pictures from the ERD:
New item_template table:
![image](https://cloud.githubusercontent.com/assets/23045206/26764259/93912eda-4918-11e7-8a30-1caf9f16b46d.png)
Old item_template table:
![image](https://cloud.githubusercontent.com/assets/23045206/26764295/2430f696-4919-11e7-970c-4bd7739f867e.png)

**Comment by klondikemarlen** [comment]
This would also make all of the Proficiency sub-classes into one table.

**Comment by elthran** [comment]
So as I read it, instead of sub-classes, each weapon just has booleans for each possible value and therefore one simple, long table is sufficient to store all the data for each piece of equipment?

**Comment by klondikemarlen** [comment]
What you said exactly. And if one weapon has more fields ... the other weapons just leave those blank.

**Comment by klondikemarlen** [comment]
Mostly implemented. I might tweak Proficiencies if I can figure out how.
