### ISSUE TITLE
Second hero

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#225]
Even though this function is probably never going to be used, I want to play with it since you have separated user from hero for this purpose. I will make it an admin account only feature where you can create multiple heroes. The main purpose is just for me to understand how to separate the two from each other and it's a learning exercise.

**Comment by klondikemarlen** [comment]
:) 👍

**Comment by klondikemarlen** [comment]
See issue_225

**Comment by klondikemarlen** [comment]
Debugging Hero selection dialogue now. Most of the rest should be working. I might need some help.

**Comment by klondikemarlen** [comment]
Fixed in  e5c5885
