### ISSUE TITLE
Images not working correctly

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#250]
Currently the image name is using location.page_name to generate the image. So whatever you set this variable, it will use that to grab the image. So in your code I see you have created this variable (shown here) 
![piccy](https://user-images.githubusercontent.com/11773722/34322300-495bbd3a-e7d8-11e7-98f4-a8a8d66b5d6b.jpg)

But it never actually calls that variable. It calls the page_name.

**Comment by elthran** [comment]
I found the bug. In locations.py you are overriding page image with the type of the location. 
![piccy](https://user-images.githubusercontent.com/11773722/34322519-e4dbef46-e7dd-11e7-87e6-4799246012b3.jpg)

This needs to not happen if the prebuilt object already has a page_image variable. Here I declare the page_image in prebuilt objects: 
![piccy](https://user-images.githubusercontent.com/11773722/34322530-0a5f3728-e7de-11e7-9d50-b7dd65ea16e8.jpg)

But your code above overwrites this in the database.

**Comment by klondikemarlen** [comment]
This was a multi-part bug. 

1. The `location.update()` function was running on object load (`@orm.reconstructor`) and 
2. `cave.page_image` was being used instead of `cave.display.page_image`
3. update() function was being run after modifying the image. It then erased the customized image.
