### ISSUE TITLE
Changing location on death

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#256]
When you die, you should be returned to the last city you visited (not just city, but only certain types of terrain. For example, if you die exploring the cave you should come back to life either at the cave entrance or in the town. If you die in the arena you shouldnt come back to life but in the town. Maybe more specifically, you come back to life in the last 'hospital' you visited - whether that be the town's healer or whatnot). It almost works right now: 
![piccy](https://user-images.githubusercontent.com/11773722/34324170-6475c76a-e81d-11e7-8951-e3dfa73cf405.jpg)
But this seems to update itself. I would prefer that this didnt update at all. Here is where it should happen: 
![piccy](https://user-images.githubusercontent.com/11773722/34324172-8a5a0a22-e81d-11e7-83c7-e097c9eb2e5f.jpg)
That way we can easily declare which location type counts as a 'save point'. But the code in the first picture seems to override this code.

**Comment by klondikemarlen** [comment]
I think your problem here is a naming conflict.
 Yes .. you are using the same Foreign Key for both current_city and last_city. Which essentially ... makes these the same value.
