### ISSUE TITLE
Can't explore world map if not admin

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#260]
![coding_pic](https://user-images.githubusercontent.com/11773722/34329620-44356e20-e8bc-11e7-87c5-70be4f91c429.jpg)

Right now new accounts cant get to the cave :'(

**Comment by klondikemarlen** [comment]
Scrap the 'url_protect' code/module for now.

**Comment by elthran** [comment]
Can you do that? Or just disable it? Then you can close this issue :D

**Comment by klondikemarlen** [comment]
I disabled 'url_protect'. It now does nothing. When we renable it. I would like to move it into the 
'@app.before_request' function when we renable it.
