### ISSUE TITLE
See others users on the map

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#261]
If you are on the same location as another user, it should tell you. For towns this might be handled differently since there would be many more (maybe a town hall link where you can see them all or something). But in the wilderness, under "Things of Interest at this Location", it should show you other users here and let you see their profile.

**Comment by klondikemarlen** [comment]
Should be able to implement like so:
```
other_heroes = [for other_hero in hero.current_location.heroes_by_current_location if hero.id != other_hero.id]
```

**Comment by klondikemarlen** [comment]
You would need some display code:

`return render_template(page_links=other_heroes + what_ever_else)`

On html page:

```
{% for obj in page_links %}
    {{ obj }}
```
