### ISSUE TITLE
Profile page html is bugged

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#293]
The proficiency/attributes/abilities pages have improperly sized images which are inconsistent and make the page look like shit. Needs to be fixed.

**Comment by klondikemarlen** [comment]
Sounds like a plan. I have resized a bunch of the item images ... but yeah ... size optimization will increase page loads for sure!

**Comment by elthran** [comment]
Well, the images are removed completely! So this is no longer an issue. When I re-add the images later I will try to do it properly :)
