### ISSUE TITLE
Move the proficiency update button

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#300]
Line 30-35 of profile_proficiencies we are moving the green level up button on proficiencies. It should now only appear once on the page: where the description of a clicked prof is. So you can click on a prof to read about it, and if it's not max level AND you have prof points to spend, below the description should be a level up button.

**Comment by klondikemarlen** [comment]
Fixed in 6528795. I still want the button to be prettier though ...
I am not sure about my implementation. There is a lot of HTML template code in proficiencies.py .. it might be hard to find later. Maybe we could move the template to the templates folder?
