### ISSUE TITLE
Proficiency/Ability problem. Abilities are getting counted at level 0

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#313]
For this test I have created health and stealth to have EXACTLY the same parameters. They both should start at 5 and increase by 2 each time the proficiency levels up. I AM TESTING hero.get_summed_proficiencies()

I have also created an ability which affects each (Relentless for Health and Trickster for Stealth). These abilities should add 3 to their corresponding proficiency once the ability is learned. (ie. Health starts at 5. You can increase it by 2 if you add points to the Prof Health or you can increase it by 3 by adding points to the Ability Relentless).

By using the numbers 5, 2, and 3, it should be easy to see what's happening.

Upon launching the game, these are the values:

**Health/Stealth:** 
- base = 8 (Note, this should be 5 and should only increment by 2's unless I'm mistaken. The bug should be here)
- current = (Stealth stays at 5, Health starts at 5 and correctly heals up to 8)
- final = 8 (Should be 5, but if the base is wrong then technically this is correctly working. Doesn't seem bugged.)
- level = 0 (Correct)
- modifier = 0  (Correct)
- next_value = 10 (Correct)
**Note: Stealth has "percent = 62" for some reason. This is because it is checking that its 5/8. But not idea why it does this.**

By adding one point to Relentless Ability (should add 3 to max health) or Trickster, NOTHING happens.

Adding a second point to one of these does these changes:
- base = 11
- next_value = 13

CLEAN START -f (deleted all of the Ability points which were added)
Now adding proficiency points does these changes:
- final = 10
- level = 1
- next_value = 12
* Note: Adding a point to Stealth changes to "current = 7"

Adding a second point does these changes:
- final = 12
- level = 2
- next_value = 14

FINAL ASSESSMENT

There are no bugs with adding proficiency points. Adding ability points also seems bug free. The problem seems to be that proficiencies treat "ability.level == 0" as though it were "ability.level == 1". This seems to be the only bug. The main problem seems to be that the BASE value is using the ability when it shouldn't. The BASE value should completely ignore abilities and just be 5. But it is 8 here. At game launch BASE should be 5 and FINAL should be 5. After learning level 1 of Relentless/Trickster it should be BASE is 5 and FINAL is 8. That was my understanding.

**Comment by klondikemarlen** [comment]
I'm not sure this is fixed .. I guess I auto-closed this issue with my commit statement?
