### ISSUE TITLE
Issue with number of decimals in items/proficiencies

### ISSUE THREAD

**Issue by elthran** [elthran/RPG-Game#344]
We have an item called Rusty Dagger. 
![coding](https://user-images.githubusercontent.com/11773722/39495788-aab18668-4d50-11e8-9618-4b503302ef30.jpg)

It Should add 7 to your Strength (aka max damage) and 0.6 to your Speed. However, this is what the tooltip shows: 
![coding](https://user-images.githubusercontent.com/11773722/39495815-c902b830-4d50-11e8-9448-9152733544a8.jpg)

The tooltip shows it will add 7 Strength and 1 Speed. It rounds the speed to an integer.
![coding](https://user-images.githubusercontent.com/11773722/39495850-f9b4b424-4d50-11e8-88b2-48b81500a51e.jpg)

And you can see it's not just the tooltip, but it actually adds 1 to your Speed value. (I've tested with other values, it always rounds to an integer. It has nothing to do with the number 1).

Andif I check the Speed proficiency we can see that it shoul dbe rounding to 3 decimal places. So the error is not there:
![coding](https://user-images.githubusercontent.com/11773722/39495918-461c7e50-4d51-11e8-8ff8-445b13794b68.jpg)

Please help me find the bug here @klondikemarlen 

Here is my last commit which tweaked some of the values while searching for the bug:
https://github.com/elthran/RPG-Game/commit/903316d576eb7d6b5fea330d0bdfb4db278767bc

**Comment by elthran** [comment]
On a related note, here is our gnarled staff:
![coding](https://user-images.githubusercontent.com/11773722/39496196-48355512-4d52-11e8-8cb0-d1cb5ae55d13.jpg)
Shouls add 15 to Strength and then +100% to your Combat (ie. double it).

But it does this and I have no idea why!
![coding](https://user-images.githubusercontent.com/11773722/39496217-60ce2a72-4d52-11e8-90e5-83249948b07b.jpg)
It adds +1 to your Combat and then adds +100% to it. Then it adds the 15 Strength. In other words, it works bug free and does what I want it to, but I have no idea why it adds +1 to Combat. I never told it to do that anywhere? It must do it by default but I haven't seen where it does that yet.

**Comment by elthran** [comment]
Note, if I change it to this:
![coding](https://user-images.githubusercontent.com/11773722/39496344-d35a0dea-4d52-11e8-8f56-ea9acf2c9a20.jpg)

I still get this:
![coding](https://user-images.githubusercontent.com/11773722/39496355-df9c0518-4d52-11e8-84ae-137ecd79c4f9.jpg)

So if you add a modifier, then the base value always seems to default to 1. But if you don't add a modifier, then you have full control of the base.

**Comment by klondikemarlen** [comment]
Combat bug fixed in: https://github.com/elthran/RPG-Game/commit/76deaf7313833a6e9ee5e54275095d544a147c5c
Speed bug fixed in: https://github.com/elthran/RPG-Game/commit/95a2874977b9e15f43f218572b7dccef4200fe26
