### ISSUE TITLE
Make the database record email and associate that with users

### ISSUE THREAD

**Issue by jimmy-gnahz** [elthran/RPG-Game#46]
This is tied to Issue #21

**Comment by elthran** [comment]
Are you trying to say that you are going to do them both at the same time?! :dancer:

**Comment by jimmy-gnahz** [comment]
Yes so it will look like I closed two issues

**Comment by klondikemarlen** [comment]
I implemented this in the database_v3 but I haven't updated the login page to allow the user to actually enter an email address. It can be stored though.

**Comment by klondikemarlen** [comment]
Implemented in database ... now all we need is the html and app code to hook in.

**Comment by klondikemarlen** [comment]
I believe that we should implement some kind of real hashing/encryption scheme before implementing this. The email addresses should be stored in an encrypted format. Salted-hashes or something. Unlocked with the Users password (also encrypted Salted-hashes). See bycrypt module. See issue #203.

**Comment by klondikemarlen** [comment]
Implemented in security branch. Now merged into master https://github.com/elthran/RPG-Game/pull/316
